//Hive Type
const HIVE_TYPE_USER_VO = 1;

const HIVE_TYPE_CARD_VO = 2;

const HIVE_TYPE_MOVIE_VO=3;

const HIVE_TYPE_BELONGS_TO_COLLECTION=4;

const HIVE_TYPE_GERNE_VO=5;

const HIVE_TYPE_PRODUCTION_COMPANIES=6;

const HIVE_TYPE_PRODUCTION_COUNTRIES=7;

const HIVE_TYPE_SPOKEN_LANGUAGES=8;

const HIVE_TYPE_ACTOR_VO=9;

const HIVE_TYPE_SNACK_VO=10;

const HIVE_TYPE_DAYTIME_SLOTS_VO=11;

const HIVE_TYPE_TIME_SLOTS_VO=12;

//Hive Box

const BOX_NAME_USER_VO = 'BOX_NAME_USER_VO';

const BOX_NAME_CARD_VO = 'BOX_NAME_CARD_VO';

const BOX_NAME_MOVIE_VO='BOX_NAME_MOVIE_VO';

const BOX_NAME_ACTOR_VO='BOX_NAME_ACTOR_VO';

const BOX_NAME_SNACK_VO='BOX_NAME_SNACK_VO';

const BOX_NAME_PAYMENT_VO='BOX_NAME_PAYMENT_VO';

const BOX_NAME_DAY_TIMESLOTS_VO='BOX_NAME_DAY_TIMESLOTS';




