class EnvironmentConfig {
  // static const String CONFIG_THEME_COLOR = String.fromEnvironment(
  //     "CONFIG_THEME_COLOR",
  //     defaultValue: "COLOR_MOVIE_BOOKING_APP_PRIMARY");


  ///MOVIE_BOOKING_APP
  ///flutter run --dart-define=CONFIG_THEME_COLOR=COLOR_MOVIE_BOOKING_APP_BLACK --dart-define=CONFIG_IS_GALAXY_APP=IS_MOVIE_BOOKING_APP_BLACK

static const String CONFIG_THEME_COLOR = String.fromEnvironment(
    "CONFIG_THEME_COLOR",
    defaultValue: "COLOR_MOVIE_BOOKING_APP_PRIMARY");

static const String CONFIG_IS_GALAXY_APP = String.fromEnvironment(
    "CONFIG_IS_GALAXY_APP",
    defaultValue: "IS_GALAXY_MOVIE_BOOKING_APP");

static const String CONFIG_IS_GALAXY_APP_DESIGN = String.fromEnvironment(
    "CONFIG_IS_GALAXY_APP_DESIGN",
    defaultValue: "IS_GALAXY_MOVIE_DESIGN_VIEW");

static const String CONFIG_ACTOR_ROW_DESIGN = String.fromEnvironment(
    "CONFIG_ACTOR_ROW_DESIGN",
    defaultValue: "IS_GALAXY_MOVIE_ACTOR_VIEW");

static const String CONFIG_SEAT_COLOR = String.fromEnvironment(
    "CONFIG_SEAT_COLOR",
    defaultValue: "GALAXY_MOVIE_SEAT_COLOR");

static const String CONFIG_CARD_CAROUSAL_VIEW = String.fromEnvironment(
    "CONFIG_CARD_CAROUSAL_VIEW",
    defaultValue: "IS_GALAXY_MOVIE_CARD_CAROUSAL_VIEW");


  ///flutter run --dart-define=CONFIG_THEME_COLOR=COLOR_MOVIE_BOOKING_APP_BLACK --dart-define=CONFIG_IS_GALAXY_APP=IS_MOVIE_BOOKING_APP_BLACK   --dart-define=CONFIG_IS_GALAXY_APP_DESIGN=IS_MOVIE_BOOKING_APP_DESIGN_VIEW --dart-define=CONFIG_ACTOR_ROW_DESIGN=IS_MOVIE_BOOKING_APP_ACTOR_VIEW --dart-define=CONFIG_SEAT_COLOR=MOVIE_BOOKING_APP_ACTOR_VIEW  --dart-define=CONFIG_CARD_CAROUSAL_VIEW=IS_MOVIE_BOOKING_APP_CARD_CAROUSAL_VIEW

///flutter run --dart-define=CONFIG_THEME_COLOR=COLOR_MOVIE_BOOKING_APP_PRIMARY --dart-define=CONFIG_IS_GALAXY_APP=IS_GALAXY_MOVIE_BOOKING_APP   --dart-define=CONFIG_IS_GALAXY_APP_DESIGN=IS_GALAXY_MOVIE_DESIGN_VIEW --dart-define=CONFIG_ACTOR_ROW_DESIGN=IS_GALAXY_MOVIE_ACTOR_VIEW --dart-define=CONFIG_SEAT_COLOR=GALAXY_MOVIE_SEAT_COLOR  --dart-define=CONFIG_CARD_CAROUSAL_VIEW=IS_GALAXY_MOVIE_CARD_CAROUSAL_VIEW
}

